kind: pipeline
type: docker
name: default

steps:
  - name: build_image
    image: docker
    volumes:
      - name : build_docker
        path: /var/run/docker.sock
    commands :
      - docker build docker/ -t ubuntu_glish3

  - name: build_api
    image: ubuntu_glish3
    pull: never
    commands:
      - mkdir build || exit 0
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Release ..
      - cmake --build . --target glish3

  - name: package
    image: ubuntu_glish3
    pull: never
    commands:
      - cd build && cpack
    when:
      event: tag

volumes:
  - name: build_docker
    host:
      path: /var/run/docker.sock